### ISSUE TITLE
Suggestions and Feed Back link is wrong

### ISSUE THREAD

**Issue by echeadle** [PacktPublishing/Go-Systems-Programming#1]
Clicking the Suggestions and Feedback link at the bottom of the README.md file takes you to a page titled:   Beginning Object-Oriented Programming with JavaScript

The book is great.  I do have two suggestions, so I thought I would put them here since the Feedback page might not get to you.

You might let the people know the use of SIGINFO in cpSignal.go is a mac only thing.  Linux you have to use something else. I am tracking it down now.  

Also, I don't have apache running and there are some other data files I had to reconstruct.  You might put some test files up on this site, so people can concentrate on the code.  If they got the same result as is in the book they know it works like you intended.

All in all, I have a number of books on go. They are good books, but I come from a system's administration backgroud, so the systems programming works great for me.

**Comment by packtBhagyashree** [comment]
Hi Edward,

Thanks for raising the issue regarding the Suggestions and Feedback page. We are working on it. I am glad that you liked the book.

You are right regarding SIGINFO. On Linux machines, you should replace syscall.SIGINFO with another signal such as syscall.SIGUSR1 and syscall.SIGUSR2.

To address your second query, I have uploaded a file with some Apache log entries that can be used for testing. You can find the file here:
https://github.com/PacktPublishing/Go-Systems-Programming/blob/master/ApacheLogs.txt

Cheers

**Comment by echeadle** [comment]
Thanks for logs and the information.  I consider this issue closed.

**Comment by echeadle** [comment]
Thanks for the Apache logs.  I think it helps keep people on track with learning go instead of getting sidetracked with Apache.   Good luck with the book.
