### ISSUE TITLE
The wc program on chapter 6 fails when the last line of a file does not terminate with a new line character

### ISSUE THREAD

**Issue by pirivan** [PacktPublishing/Go-Systems-Programming#3]
When the last line of a file does not terminate with the new line character the program fails to include that line's content into the count of number of words and characters. You can take a look at my fixes in these two commits.

https://gitlab.com/pirivan/golearn/commit/dfeb4b856fb135b292590de6ed2f403768be6a65
https://gitlab.com/pirivan/golearn/commit/2459b220e486dbf85db82f30b5d1e49523c3bfa0

**Comment by mactsouk** [comment]
Made the PR in https://github.com/PacktPublishing/Go-Systems-Programming/pull/4
Thanks!

**Comment by pirivan** [comment]
I'm glad to help. BTW, after fixing the bug my next change was to move the compilation of the regexp expression to the main body of the program so that it is done only once; there is no point in doing it over and over again. That change alone sped up the program substantially!

Details of this update, and my final "speedy" version of the program are available from my Gitlab repo.
Cheers,
--
Pedro

On Jul 9 2018, at 3:04 pm, Mihalis Tsoukalos <notifications@github.com> wrote:
>
> Made the PR in #4 (https://link.getmailspring.com/link/1531173381.local-eedc02bf-8d9b-v1.2.2-96fb3a99@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2FPacktPublishing%2FGo-Systems-Programming%2Fpull%2F4&recipient=cmVwbHkrMDE1MzVmNWM4ZTk3ZTZjMDlmZDI5MjU0NTJhMmVmYTIwOWQ0ZGJkNGUzZmI0YWQ1OTJjZjAwMDAwMDAxMTc1YjczZDE5MmExNjljZTE0M2NlNzhiQHJlcGx5LmdpdGh1Yi5jb20%3D)
Thanks!

**Comment by techsachinkumar** [comment]
Merged pull request

Closed.
